const DAY_IN_MILLISECONDS = 24 * 60 * 60 * 1000;
const ERROR_CODES = {
  DUPLICATED: 'ER_DUP_ENTRY',
  IS_REFERENCED: 'ER_ROW_IS_REFERENCED_2'
}

module.exports = {
  DAY_IN_MILLISECONDS,
  ERROR_CODES
}